"""init schema

Revision ID: 135319e80f45
Revises: 
Create Date: 2025-11-11 22:06:50.821556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135319e80f45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_athletes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('weight_category', sa.String(), nullable=False),
    sa.Column('entry_total', sa.Float(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('applications', sa.Column('federation_id', sa.UUID(), nullable=False))
    application_type = sa.Enum('preliminary', 'final', name='applicationtype')
    application_type.create(op.get_bind(), checkfirst=True)
    #op.add_column('applications', sa.Column('type', application_type, nullable=True))
    op.add_column('applications', sa.Column('type', sa.Enum('preliminary', 'final', name='applicationtype'), nullable=True))
    op.add_column('applications', sa.Column('submission_date', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('applications', 'competition_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('applications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('applications_competition_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'competitions', ['competition_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'federations', ['federation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('applications', 'profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('profile', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('applications_competition_id_fkey'), 'applications', 'competitions', ['competition_id'], ['id'])
    op.alter_column('applications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('applications', 'competition_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('applications', 'created_at')
    op.drop_column('applications', 'submission_date')
    op.drop_column('applications', 'type')
    op.drop_column('applications', 'federation_id')
    op.drop_table('application_staff')
    op.drop_table('application_athletes')
    op.drop_table('federations')
    # ### end Alembic commands ###
