"""athlete form

Revision ID: 2aa19fe3a8fb
Revises: 135319e80f45
Create Date: 2025-11-19 20:01:06.635526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa19fe3a8fb'
down_revision: Union[str, Sequence[str], None] = '135319e80f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_athletes', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('application_athletes', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('application_athletes', sa.Column('middle_name', sa.String(), nullable=True))
    op.drop_column('application_athletes', 'full_name')
    op.create_foreign_key(None, 'applications', 'users', ['submitted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.add_column('application_athletes', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('application_athletes', 'middle_name')
    op.drop_column('application_athletes', 'first_name')
    op.drop_column('application_athletes', 'last_name')
    # ### end Alembic commands ###
